version: '3'

services:
  mongo:
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo_config:/data/configdb
    ports:
      - 27017:27017

  app:
    build: .
    environment:
      - DOCKER_MONGO=mongo
    command: invoke create-database start-dash-app
    depends_on:
      - mongo
    ports:
      - 8000:8000