version: '3'

services:
  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017

  app:
    build: .
    environment:
      - DOCKER_MONGO=mongo
    command: invoke create-database start-dash-app
    depends_on:
      - mongo
    ports:
      - 8050:8050